### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tujintianxiaren** [MingLaoShi/BlueArchiveTwinsMod#7]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:188)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:55)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
	at com.badlogic.gdx.graphics.g3d.loader.G3dModelLoader.parseModel(G3dModelLoader.java:65)
	at com.badlogic.gdx.graphics.g3d.loader.G3dModelLoader.loadModelData(G3dModelLoader.java:61)
	at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:53)
	at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:69)
	at baModDeveloper.helpers.ModelController.<init>(ModelController.java:28)
	at baModDeveloper.helpers.CharacterMaidHelper.init(CharacterMaidHelper.java:33)
	at baModDeveloper.helpers.Character3DHelper.<init>(Character3DHelper.java:43)
	at baModDeveloper.helpers.CharacterMaidHelper.<init>(CharacterMaidHelper.java:12)
	at baModDeveloper.character.BATwinsCharacter.<clinit>(BATwinsCharacter.java:119)
	at baModDeveloper.BATwinsMod.receiveEditCharacters(BATwinsMod.java:266)
	at basemod.BaseMod.publishEditCharacters(BaseMod.java:2553)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.EditCharactersHook.Insert(EditCharactersHook.java:20)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:299)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by MewKon** [comment]
分配给尖塔的内存不足，可以C:\Users\AppData\Local\ModTheSpire\BATwinsMod下的文件删除，然后启动游戏取消角色的开启3D模型选项就能正常游戏
